id: I7E7E5B81
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T16:44:12+00:00'
last_modified: '2022-06-07T21:38:02.978155+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29059
  title: གསུང་འབུམ། མདོ་སྔགས་བསྟན་པའི་ཉི་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3077':
      image_group_id: I5695
      title: ''
      total_pages: 355
      order: 1
      base_file: 3077.txt
    5FC8:
      image_group_id: I5696
      title: ''
      total_pages: 357
      order: 2
      base_file: 5FC8.txt
    '6387':
      image_group_id: I5697
      title: ''
      total_pages: 334
      order: 3
      base_file: 6387.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
